package ru.fraudcore.audit.entity;

public enum AuditAction {
    TRANSACTION_RECEIVED,
    TRANSACTION_APPROVED,
    TRANSACTION_TEMPORARILY_BLOCKED,
    CASE_CREATED,
    CASE_ASSIGNED,
    CASE_DECISION_MADE,
    CASE_CLOSED,
    KAFKA_EVENT_PUBLISHED,
    KAFKA_EVENT_CONSUMED
}
